import type { NextPage } from "next";
import { useRouter } from "next/router";
import Head from "next/head";
import { MDXRemote } from "next-mdx-remote";

import { Header } from "@/components/header";
import { SearchBox } from "@/components/search-box";
import { api } from "@/utils/api";

export const config = {
  unstable_includeFiles: ["node_modules/.pnpm/**/shiki/**/*.json"],
};

const RewritePage: NextPage = () => {
  const { query } = useRouter();

  const rewrite = api.rewrites.getOne.useQuery({
    name: query.name as string,
  });

  const github = rewrite.data?.github
    ?.replace(/https:\/\/github.com\//, "")
    .split("/");

  const readme = api.github.getReadme.useQuery(
    {
      owner: github?.[0] || "",
      repo: github?.[1] || "",
    },
    {
      enabled: !!github,
    }
  );

  return (
    <>
      <Head>
        <title>Rewrite it in Rust - {rewrite.data?.name}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header>
        <SearchBox small />
      </Header>
      <main className="grid min-h-screen grid-rows-[min-content_1fr]">
        <section className="grid h-full grid-cols-[1fr_minmax(0,1024px)_1fr] grid-rows-[min-content_1fr] bg-slate-700 px-6 text-slate-300 sm:px-12">
          <section className="col-start-2 flex flex-col items-baseline gap-2 p-8">
            <h1 className="min-h-max text-2xl font-bold sm:text-3xl">
              {rewrite.data?.name}
            </h1>
            <h2 className="text-lg sm:text-xl">{rewrite.data?.description}</h2>
          </section>
        </section>
        <section className="min-h-full w-screen bg-slate-300 p-6 sm:p-12">
          <div className="prose prose-slate mx-auto max-w-3xl">
            {readme.data && <MDXRemote {...readme.data}></MDXRemote>}
          </div>
        </section>
      </main>
    </>
  );
};

export default RewritePage;
