import type { NextPage } from "next";
import { useRouter } from "next/router";
import Head from "next/head";

import { Header } from "@/components/header";
import { SearchBox } from "@/components/search-box";
import { api } from "@/utils/api";
import { Box, ExternalLink, Flame, Github, Loader2 } from "lucide-react";
import {
  formatCratesUrl,
  formatGithubUrl,
  formatUrl,
} from "@/utils/format-url";
import { useEffect } from "react";

const RewritePage: NextPage = () => {
  const { query } = useRouter();

  const { data: rewrite } = api.rewrites.getOne.useQuery({
    name: query.name as string,
  });

  const readme = api.github.getReadme.useQuery(
    { url: rewrite?.github as string },
    { enabled: !!rewrite?.github }
  );

  const { mutate: incrementViews } = api.rewrites.incrementViews.useMutation();

  useEffect(() => {
    if (rewrite?.name) {
      incrementViews({
        name: rewrite.name,
      });
    }
  }, [rewrite?.name, incrementViews]);

  return (
    <>
      <Head>
        <title>Rewrite it in Rust - {rewrite?.name}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header>
        <SearchBox small />
      </Header>
      <main className="grid min-h-screen grid-rows-[min-content_1fr]">
        <section className="grid h-full grid-cols-[1fr_minmax(0,800px)_1fr] grid-rows-[min-content_1fr] bg-slate-700 px-6 text-slate-300 sm:px-12">
          <section className="col-start-2 flex flex-col gap-2 py-10">
            {!rewrite ? (
              <>
                <div className="h-8 w-28 animate-pulse rounded-sm bg-slate-500/80" />
                <div className="h-8 w-[36rem] max-w-full animate-pulse rounded-sm bg-slate-500/80" />
                <div className="h-6 w-96 animate-pulse rounded-sm bg-slate-400/80" />
              </>
            ) : (
              <>
                <h1 className="text-2xl font-bold sm:text-3xl">
                  {rewrite.name}
                </h1>
                <h2 className="text-lg sm:text-xl">{rewrite.description}</h2>
                <div className="flex flex-wrap gap-4 text-slate-400">
                  {rewrite.url && (
                    <a
                      href={rewrite.url}
                      target="_blank"
                      rel="noreferrer"
                      className="flex items-center gap-1 hover:text-slate-100 hover:underline"
                    >
                      <ExternalLink className="h-5 w-5" />
                      <span>{formatUrl(rewrite.url)}</span>
                    </a>
                  )}
                  {rewrite.github && (
                    <a
                      href={rewrite.github}
                      target="_blank"
                      rel="noreferrer"
                      className="flex items-center gap-1 hover:text-slate-100 hover:underline"
                    >
                      <Github className="h-5 w-5" />
                      <span>{formatGithubUrl(rewrite.github)}</span>
                    </a>
                  )}
                  {rewrite.crates && (
                    <a
                      href={rewrite.crates}
                      target="_blank"
                      rel="noreferrer"
                      className="flex items-center gap-1 hover:text-slate-100 hover:underline"
                    >
                      <Box className="h-5 w-5" />
                      <span>{formatCratesUrl(rewrite.crates)}</span>
                    </a>
                  )}
                  <div className="flex items-center gap-1">
                    <Flame className="h-5 w-5" />
                    <span>{rewrite.views} views</span>
                  </div>
                </div>
              </>
            )}
          </section>
        </section>
        <section className="min-h-full w-screen bg-slate-300 p-6 sm:p-12">
          <div className="prose prose-slate mx-auto max-w-3xl">
            {rewrite && !rewrite.github && <p>No README found.</p>}
            {readme.isFetching ? (
              <Loader2 className="mx-auto h-10 w-10 animate-spin" />
            ) : readme.isError ? (
              <p>Error: {readme.error.message}</p>
            ) : (
              <section
                // TODO: find a better way to do this
                dangerouslySetInnerHTML={{ __html: readme.data ?? "" }}
              />
            )}
          </div>
        </section>
      </main>
    </>
  );
};

export default RewritePage;
